### ISSUE TITLE
Feature: Video Profile für verschiedene Ausgabeformate

### ISSUE THREAD

**Issue by omphteliba** [FriendsOfREDAXO/ffmpeg#3]
Damit man wiederkehrende Umwandlungen verschiedene Ausgabeformate (zB für WebM, mit und ohne Ton, OGV...) ablegen kann.

Beispiele:
WebM:
`.\ffmpeg -i input.mp4 -c:v libvpx-vp9 -crf 30 -b:v 0 -b:a 128k -c:a libopus output.webm`
`.\ffmpeg -i input.mp4 -c:v libvpx-vp9 -crf 30 -b:v 0 output.webm // ohne Audio`

OGV: 
`.\ffmpeg.exe -i input.mp4 -codec:v libtheora -qscale:v 6 -codec:a libvorbis -qscale:a 6 output.ogv`

**Comment by skerbis** [comment]
Gerne PR einreichen. Ich close hier erstmal. Von meiner Seite erstmal nicht geplant.
